#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release
release:
  version: 0.16.0
managers:
  bundles:
  - artifact: dev.galasa.zos3270.managers
    bom: true
    version: 0.16.0
    mvp: true
external:
  bundles:
  - group: commons-io
    artifact: commons-io
    version: 2.6
    bom: true
    obr: true
    mvp: true
    isolated: true